url: "https://josephhaddad55.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/learning-arabic" # the subpath of your site, e.g. /blog
title: "Learning Arabic" # the name of your site, e.g. ACME Corp.
